[workspace]
members = [
  "crates/onda_cli",
  "crates/onda_daemon",
  "crates/onda_frontend",
  "crates/onda_semantics",
  "crates/onda_codegen_llvm",
  "crates/onda_runtime",
  "crates/onda_api",
  "crates/onda_preview",
  "crates/onda_egui",
  "crates/onda_webview",
  "crates/onda_examples",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "0.1.0"
authors = ["onda contributors"]

[workspace.lints.clippy]
unwrap_used = "deny"
