[package]
name = "omni_codegen_llvm"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[features]
default = ["llvm-orc"]
llvm-orc = ["dep:llvm-sys"]

[dependencies]
omni_frontend = { path = "../omni_frontend" }
omni_semantics = { path = "../omni_semantics" }
llvm-sys = { version = "211.0.0", optional = true, features = ["no-llvm-linking"] }

[lib]
path = "src/lib.rs"
