[package]
name = "omni_api"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
omni_frontend = { path = "../omni_frontend" }
omni_semantics = { path = "../omni_semantics" }
omni_codegen_llvm = { path = "../omni_codegen_llvm" }
omni_runtime = { path = "../omni_runtime" }
