[package]
name = "onda_runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
onda_codegen_llvm = { path = "../onda_codegen_llvm" }
onda_frontend = { path = "../onda_frontend" }
onda_realtime = { path = "../onda_realtime" }

[dev-dependencies]
onda_semantics = { path = "../onda_semantics" }

[lib]
path = "src/lib.rs"
