[env]
LLVM_SYS_211_PREFIX = { value = ".deps/llvm-src/21.1.2-static", relative = true }
ONDA_LLVM_LINK_MODE = { value = "static" }

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
