import { readFile } from "node:fs/promises";

import {
  compileTrustedMir as compileMir,
  createDefaultImports,
} from "../src/index.js";

const mirPath = process.argv[2];
if (!mirPath) {
  throw new Error("usage: npm run verify-mir -- <program.mir.json>");
}

const artifact = compileMir(await readFile(mirPath, "utf8"));
if (!WebAssembly.validate(artifact.wasm)) {
  throw new Error("generated bytes are not a valid WebAssembly module");
}

const { instance } = await WebAssembly.instantiate(
  artifact.wasm,
  createDefaultImports(),
);
const { memory, __heap_base, onda_init, onda_process } = instance.exports;
const blockSize = artifact.metadata.compile.block_size;
const outputCount = artifact.metadata.metadata.outputs.reduce(
  (count, output) => count + output.array_len,
  0,
);
let heap = Number(__heap_base.value);
const allocate = (bytes, alignment = 16) => {
  heap = Math.ceil(heap / alignment) * alignment;
  const address = heap;
  heap += bytes;
  const requiredPages = Math.ceil(heap / (64 * 1024));
  const currentPages = memory.buffer.byteLength / (64 * 1024);
  if (requiredPages > currentPages) memory.grow(requiredPages - currentPages);
  return address;
};

const params = allocate(Math.max(4, artifact.metadata.runtime.param_size_bytes));
const state = allocate(artifact.metadata.runtime.state_size_bytes);
const outputTable = allocate(outputCount * 4, 4);
const view = new DataView(memory.buffer);
for (const param of artifact.metadata.metadata.params) {
  if (param.scalar === "f32" && param.default_reprs?.length === 1) {
    view.setFloat32(params + param.byte_offset, JSON.parse(param.default_reprs[0]), true);
  }
}

const outputPointers = [];
for (let channel = 0; channel < outputCount; channel += 1) {
  const pointer = allocate(blockSize * 4);
  outputPointers.push(pointer);
  new DataView(memory.buffer).setUint32(outputTable + channel * 4, pointer, true);
}

onda_init(params, state);
onda_process(state, params, 0, outputTable, 0, blockSize, 3, 0, 0, 0, 0);
const samples = outputPointers.flatMap((pointer) => [
  ...new Float32Array(memory.buffer, pointer, blockSize),
]);
const peak = samples.reduce((value, sample) => Math.max(value, Math.abs(sample)), 0);
if (!Number.isFinite(peak) || peak === 0) {
  throw new Error(`DSP smoke render has invalid peak ${peak}`);
}

process.stdout.write(
  `Verified MIR -> Binaryen -> Wasm: ${artifact.wasm.byteLength} bytes, peak ${peak.toFixed(6)}\n`,
);
